import {
  jsonb,
  pgTable,
  serial,
  text,
  timestamp,
  varchar,
} from "drizzle-orm/pg-core";

export const hittaMaklare = pgTable("hitta_maklare", {
  id: serial("id").primaryKey(),
  name: varchar("name", { length: 100 }).notNull(),
  realEstateAgency: varchar("real_estate_agency", { length: 100 }).notNull(),
  office: varchar("office", { length: 100 }).notNull(),
  county: varchar("county", { length: 100 }),
  locality: varchar("locality", { length: 100 }),
  telephone: varchar("telephone", { length: 50 }),
  email: varchar("email", { length: 100 }),
  streetAddress: varchar("street_address", { length: 200 }),
  addressLocality: varchar("address_locality", { length: 100 }),
  addressCountry: varchar("address_country", { length: 100 }),
  postalCode: varchar("postal_code", { length: 20 }),
  background: text("background"),
  presentation: jsonb("presentation"),
  ratings: jsonb("ratings"),
  reviews: jsonb("reviews"),
  urlPath: varchar("url_path", { length: 200 }).notNull().unique(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  deletedAt: timestamp("deleted_at"),
});
