// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evgzebvzrihsqfqhmwxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2Z3plYnZ6cmloc3FmcWhtd3hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0ODQ4MjQsImV4cCI6MjA3NDA2MDgyNH0.278oaiUZQFbQUk6IhLsTCvxUmN7Og3jTOrNw18I1sXs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});